from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlmodel import select
from app.core.database import get_session
from app.models.tables import Contract, ContractClause

router = APIRouter(prefix="/api/v1/reports", tags=["reports"])

@router.get("/contracts/{contract_id}/risk")
async def generate_contract_report(contract_id: str, session: AsyncSession = Depends(get_session)):
    result = await session.execute(select(Contract).where(Contract.id == contract_id))
    contract = result.scalar_one_or_none()
    if not contract:
        raise HTTPException(status_code=404, detail="Not found")

    res_clauses = await session.execute(select(ContractClause).where(ContractClause.contract_id == contract_id))
    clauses = res_clauses.scalars().all()

    report_html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Contract Report - {contract.title}</title>
    <style>
        body {{ font-family: Inter, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #0F1117; }}
        h1 {{ border-bottom: 2px solid #0F1117; padding-bottom: 10px; }}
        .meta {{ color: #8B8F9A; font-size: 14px; margin: 4px 0; }}
        .section {{ margin: 30px 0; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
        th, td {{ text-align: left; padding: 8px; border-bottom: 1px solid #E5E5E5; }}
        th {{ font-size: 12px; text-transform: uppercase; color: #8B8F9A; }}
    </style>
</head><body>
    <h1>Contract Report</h1>
    <p class="meta">Contract: <strong>{contract.title}</strong></p>
    <p class="meta">Counterparty: {contract.counterparty_name or 'N/A'}</p>
    <p class="meta">Governing Law: {contract.governing_law or 'N/A'}</p>
    <p class="meta">Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}</p>

    <div class="section">
        <h2>Clauses Extracted ({len(clauses)})</h2>
        <table><thead><tr><th>Type</th><th>Confidence</th><th>Extracted By</th></tr></thead><tbody>
        {''.join(f'<tr><td>{c.clause_type.replace("_", " ").title()}</td><td>{(c.confidence_score * 100):.0f}%</td><td>{c.extracted_by}</td></tr>' for c in clauses)}
        </tbody></table>
    </div>

    <div class="section">
        <h2>Disclaimer</h2>
        <p class="meta">This report is generated by REXI's contract analysis engine and is intended as a reference for legal review. Human lawyer approval is required for all actions. REXI is a legal process automation company, not a law firm.</p>
    </div>
</body></html>"""

    return {"report_html": report_html, "contract_title": contract.title}
