from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlmodel import select
from app.core.database import get_session
from app.models.tables import Contract, ContractClause, RiskAssessment, RiskFinding

router = APIRouter(prefix="/api/v1/reports", tags=["reports"])

@router.get("/contracts/{contract_id}/risk")
async def generate_risk_report(contract_id: str, session: AsyncSession = Depends(get_session)):
    result = await session.execute(select(Contract).where(Contract.id == contract_id))
    contract = result.scalar_one_or_none()
    if not contract:
        raise HTTPException(status_code=404, detail="Not found")

    res_clauses = await session.execute(select(ContractClause).where(ContractClause.contract_id == contract_id))
    clauses = res_clauses.scalars().all()

    res_assessments = await session.execute(
        select(RiskAssessment).where(RiskAssessment.contract_id == contract_id).order_by(RiskAssessment.created_at.desc())
    )
    latest = res_assessments.scalars().first()

    findings = []
    if latest:
        res_findings = await session.execute(select(RiskFinding).where(RiskFinding.assessment_id == latest.id))
        findings = res_findings.scalars().all()

    open_findings = [f for f in findings if not f.is_resolved]
    resolved = [f for f in findings if f.is_resolved]

    report_html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Risk Report - {contract.title}</title>
    <style>
        body {{ font-family: Inter, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #0F1117; }}
        h1 {{ border-bottom: 2px solid #0F1117; padding-bottom: 10px; }}
        .score {{ font-size: 48px; font-weight: bold; }}
        .score-high {{ color: #EF4444; }} .score-med {{ color: #F59E0B; }} .score-low {{ color: #22C55E; }}
        .finding {{ background: #F7F7F5; border-left: 4px solid #EF4444; padding: 12px; margin: 10px 0; border-radius: 4px; }}
        .finding-resolved {{ border-left-color: #22C55E; }}
        .meta {{ color: #8B8F9A; font-size: 14px; margin: 4px 0; }}
        .section {{ margin: 30px 0; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
        th, td {{ text-align: left; padding: 8px; border-bottom: 1px solid #E5E5E5; }}
        th {{ font-size: 12px; text-transform: uppercase; color: #8B8F9A; }}
    </style>
</head><body>
    <h1>Risk Assessment Report</h1>
    <p class="meta">Contract: <strong>{contract.title}</strong></p>
    <p class="meta">Counterparty: {contract.counterparty_name or 'N/A'}</p>
    <p class="meta">Governing Law: {contract.governing_law or 'N/A'}</p>
    <p class="meta">Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}</p>

    <div class="section">
        <h2>Overall Risk Score</h2>
        <div class="score {'score-high' if latest and latest.overall_score > 0.6 else 'score-med' if latest and latest.overall_score > 0.3 else 'score-low'}">
            {(latest.overall_score * 100 if latest else 0):.0f}/100
        </div>
        <p class="meta">Playbook: {(latest.playbook_score * 100 if latest else 0):.0f}% | Law: {(latest.law_score * 100 if latest else 0):.0f}% | Regulatory: {(latest.regulatory_score * 100 if latest else 0):.0f}%</p>
    </div>

    <div class="section">
        <h2>Open Findings ({len(open_findings)})</h2>
        {''.join(f'<div class="finding"><strong>{f.severity.upper()}</strong> — {f.title}<br/><span class="meta">{f.description}</span><br/><span style="color:#3B82F6">Suggestion: {f.suggested_amendment}</span></div>' for f in open_findings)}
    </div>

    <div class="section">
        <h2>Resolved Findings ({len(resolved)})</h2>
        {''.join(f'<div class="finding finding-resolved">{f.title}</div>' for f in resolved) if resolved else '<p class="meta">None</p>'}
    </div>

    <div class="section">
        <h2>Clauses Extracted ({len(clauses)})</h2>
        <table><thead><tr><th>Type</th><th>Confidence</th><th>Extracted By</th></tr></thead><tbody>
        {''.join(f'<tr><td>{c.clause_type.replace("_", " ").title()}</td><td>{(c.confidence_score * 100):.0f}%</td><td>{c.extracted_by}</td></tr>' for c in clauses)}
        </tbody></table>
    </div>

    <div class="section">
        <h2>Disclaimer</h2>
        <p class="meta">This report is generated by REXI's AI-powered risk assessment engine and is intended as suggestions for legal review. Human lawyer approval is required for all actions. REXI is a legal process automation company, not a law firm.</p>
    </div>
</body></html>"""

    return {"report_html": report_html, "contract_title": contract.title,
            "overall_score": latest.overall_score if latest else 0,
            "open_findings": len(open_findings), "resolved_findings": len(resolved)}
