"""Generate markdown output from redlines.

Produces structured markdown that works well in AI agent pipelines,
GitHub PRs, and documentation.
"""

from datetime import datetime


def generate_markdown(redlines, doc_title=None, author=None, date_str=None,
                      doc_parties=None, mode="external"):
    """
    Generate markdown from redlines.

    Args:
        redlines: List of redline dicts
        doc_title: Document title
        author: Author name
        date_str: Date string
        doc_parties: Parties description
        mode: "external" (clean, no rationale) or "internal" (full analysis)

    Returns:
        Markdown string
    """
    if date_str is None:
        date_str = datetime.now().strftime("%B %d, %Y")

    lines = []

    # Header
    title = doc_title or "Proposed Redlines"
    lines.append(f"# {title}\n")

    if mode == "internal":
        lines.append("**CONFIDENTIAL -- INTERNAL ANALYSIS -- DO NOT DISTRIBUTE**\n")

    meta = []
    if doc_parties:
        meta.append(f"**Parties:** {doc_parties}")
    if author:
        meta.append(f"**Prepared by:** {author}")
    meta.append(f"**Date:** {date_str}")
    meta.append(f"**Total changes:** {len(redlines)}")
    lines.extend(meta)
    lines.append("")

    if mode == "internal":
        # Group by tier
        grouped = {}
        for idx, rl in enumerate(redlines):
            t = rl.get("tier", 0)
            grouped.setdefault(t, []).append((idx, rl))

        tier_labels = {
            1: "Tier 1 -- Non-Starters",
            2: "Tier 2 -- Important",
            3: "Tier 3 -- Desirable",
            0: "Uncategorized",
        }

        for tier in sorted(grouped):
            label = tier_labels.get(tier, f"Tier {tier}")
            lines.append(f"\n## {label}\n")
            for idx, rl in grouped[tier]:
                lines.extend(_format_redline_md(idx, rl, internal=True))
    else:
        lines.append("---\n")
        for idx, rl in enumerate(redlines):
            lines.extend(_format_redline_md(idx, rl, internal=False))

    # Footer
    lines.append("\n---\n")
    lines.append(f"*Generated by legal-redline-tools on {date_str}*")

    return "\n".join(lines)


def _format_redline_md(idx, rl, internal=False):
    """Format a single redline as markdown."""
    lines = []
    rtype = rl["type"]
    section = rl.get("section", "")
    title = rl.get("title", "")

    # Header
    header_parts = [f"### {idx + 1}."]
    if section:
        header_parts.append(f"Section {section}")
    if title:
        header_parts.append(f"-- {title}")
    lines.append(" ".join(header_parts))
    lines.append("")

    type_label = {
        "replace": "Replacement", "delete": "Deletion",
        "insert_after": "Insertion", "add_section": "New Section"
    }.get(rtype, rtype)
    lines.append(f"**Type:** {type_label}")
    lines.append("")

    # Content
    if rtype == "replace":
        lines.append(f"**Current:** ~~{rl['old']}~~")
        lines.append("")
        lines.append(f"**Proposed:** __{rl['new']}__")
    elif rtype == "delete":
        lines.append(f"**Delete:** ~~{rl['text']}~~")
    elif rtype == "insert_after":
        lines.append(f"**After:** {rl['anchor']}")
        lines.append("")
        lines.append(f"**Insert:** __{rl['text']}__")
    elif rtype == "add_section":
        if rl.get("after_section"):
            lines.append(f"**After Section:** {rl['after_section']}")
        sec_num = rl.get("new_section_number", "NEW")
        lines.append(f"**New Section {sec_num}:** __{rl['text']}__")

    lines.append("")

    # Internal-only fields
    if internal:
        if rl.get("rationale"):
            lines.append(f"> **Rationale:** {rl['rationale']}")
            lines.append("")
        if rl.get("walkaway"):
            lines.append(f"> **Walkaway:** {rl['walkaway']}")
            lines.append("")
        if rl.get("precedent"):
            lines.append(f"> **Precedent:** {rl['precedent']}")
            lines.append("")

    lines.append("---\n")
    return lines
